# Generated by Django 4.0.4 on 2022-05-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModel',
            new_name='AddQuiz',
        ),
    ]
